[package]
name = "database-layer-actix"
version = "0.1.0"
authors = ["Jonas Keinholz <jonas@keinholz.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0.0"
